### PR TITLE
Migrate to alpine image

### PR DESCRIPTION
**Pull request by kaspernissen**
This PR tries to migrate the base image to alpine to remove a bunch of high vulnerabilities.

I've built the new image successfully, but I have no idea how it's used or even if it works.

@jweibel22 could you test it? 

It's available here: `quay.io/lunarway/avro-schema-registry:alpine`

### CODE REVIEW

**Comment by kaspernissen** [comment]
Vulnerabilities in the new image:
```
snyk container test quay.io/lunarway/avro-schema-registry:alpine --file=Dockerfile

Testing quay.io/lunarway/avro-schema-registry:alpine...

✗ Medium severity vulnerability found in musl/musl-dev
  Description: Out-of-bounds Write
  Info: https://snyk.io/vuln/SNYK-ALPINE313-MUSL-1067865
  Introduced through: musl/musl-dev@1.2.2-r0, libc-dev/libc-dev@0.7.2-r3, musl/musl-utils@1.2.2-r0, libc-dev/libc-utils@0.7.2-r3, meta-common-packages@meta
  From: musl/musl-dev@1.2.2-r0
  From: libc-dev/libc-dev@0.7.2-r3 > musl/musl-dev@1.2.2-r0
  From: musl/musl-utils@1.2.2-r0
  and 2 more...
  Introduced by your base image (ruby:2.6.6-alpine3.13)
  Fixed in: 1.2.2_pre2-r0



Organization:      squad-nasa
Package manager:   apk
Target file:       Dockerfile
Project name:      docker-image|quay.io/lunarway/avro-schema-registry
Docker image:      quay.io/lunarway/avro-schema-registry:alpine
Platform:          linux/amd64
Base image:        ruby:2.6.6-alpine3.13
Licenses:          enabled

Tested 70 dependencies for known issues, found 1 issue.

According to our scan, you are currently using the most secure version of the selected base image

Pro tip: use `--exclude-base-image-vulns` to exclude from display Docker base image vulnerabilities.

To remove this message in the future, please run `snyk config set disableSuggestions=true`
```

**Comment by kaspernissen** [comment]
Compared to the old results
```
....
omitted
....
Organization:      squad-nasa
Package manager:   deb
Target file:       Dockerfile
Project name:      docker-image|quay.io/lunarway/avro-schema-registry
Docker image:      quay.io/lunarway/avro-schema-registry:old
Platform:          linux/amd64
Base image:        ruby:2.6.6
Licenses:          enabled

Tested 414 dependencies for known issues, found 320 issues.

Base Image  Vulnerabilities  Severity
ruby:2.6.6  320              46 high, 44 medium, 230 low

Recommendations for base image upgrade:

Alternative image types
Base Image                       Vulnerabilities  Severity
ruby:3-slim-buster               58               10 high, 5 medium, 43 low
ruby:2.6-slim                    58               10 high, 5 medium, 43 low
ruby:3.0.0-preview2-slim-buster  61               12 high, 6 medium, 43 low
ruby:3.0.0-rc1-slim-buster       61               12 high, 6 medium, 43 low


Pro tip: use `--exclude-base-image-vulns` to exclude from display Docker base image vulnerabilities.

To remove this message in the future, please run `snyk config set disableSuggestions=true`
```

**Comment by eXeDK** [comment]
Very nice work @kaspernissen :-)

**Comment by Crevil** [comment]
@jweibel22 anything blocking us from moving forward with this?

**Comment by jweibel22** [comment]
> @jweibel22 anything blocking us from moving forward with this?

Yes it crashed when we tried to deploy it, I've created a trello task so we remember to pick it up.

**Review by jweibel22 — APPROVED** [review]
Notes for future self on how to bump ruby:

When ruby version changes the dependencies needs to be updated as well because what is in the Gemfile.lock will no longer be compatible.

One approach is to simply delete the Gemfile.lock from this repo and remove the `COPY Gemfile.lock` statement from the Dockerfile. That means that dependencies will be resolved during the docker build.

I did the above, but then I exec'ed into the container and overwrote the Gemfile.lock in the repo with the newly generated one from the container. This way we still have the pinned dependencies. It doesn't make much of a difference really since we don't have a ruby environment locally anyway, but at least we can see and track the dependencies....

**Pull request merged**
